#!/bin/bash
# Install (or remove) the "Send to TP6-S" macOS PDF Service.
#
# macOS PDF Services: any executable dropped into ~/Library/PDF Services/
# appears in the PDF dropdown of every app's print dialog, and the FILE'S
# NAME is the menu label. This script writes a small wrapper there named
# exactly "Send to TP6-S" that execs this machine's venv python running
# tools/pdf_service.py from THIS repo checkout.
#
# The wrapper is generated, not symlinked, because each checkout may live at
# a different path. Each Mac runs this installer once and gets a wrapper with
# that machine's paths baked in; the repository remains the source of truth.
#
# Usage:
#   ./tools/install_pdf_service.sh              install the real wrapper
#   ./tools/install_pdf_service.sh --probe      install a diagnostic wrapper
#                                                (same name/slot) that logs
#                                                every invocation instead of
#                                                printing
#   ./tools/install_pdf_service.sh --uninstall  remove the installed item
#   ./tools/install_pdf_service.sh --force      combine with the above to
#                                                overwrite an item at that
#                                                path this installer didn't
#                                                generate
#   ./tools/install_pdf_service.sh --help       this text
#
# Safe to re-run; re-running overwrites cleanly.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PDF_SERVICES_DIR="$HOME/Library/PDF Services"
TARGET="$PDF_SERVICES_DIR/Send to TP6-S"

CONFIG_DIR="$HOME/.config/tp6s"
LOG_FILE="$CONFIG_DIR/pdf-service.log"
VENV_PYTHON="$HOME/.venvs/tp6s/bin/python"

MARKER="# GENERATED by install_pdf_service.sh"

usage() {
    cat <<'USAGE'
Usage: install_pdf_service.sh [--probe | --uninstall] [--force] [--help]

  (no args)     Install the real "Send to TP6-S" PDF Service wrapper.
  --probe       Install a diagnostic wrapper under the same name instead,
                that logs every invocation to ~/.config/tp6s/pdf-service.log
                and copies the spool PDF alongside it. Used to verify the
                macOS invocation contract before the real thing prints.
  --uninstall   Remove the installed "Send to TP6-S" item, if present.
  --force       Combine with install or --probe to overwrite an item at
                that path that this installer did not generate.
  --help        Show this text.
USAGE
}

echo "== TP6-S PDF Service installer on $(hostname -s) =="
echo "repo:       $REPO_DIR"
echo "venv:       $VENV_PYTHON"
echo "wrapper at: $TARGET"
echo ""

# --- arg parsing -------------------------------------------------------

MODE="install"
FORCE=0
BAD_ARG=""

for arg in "$@"; do
    case "$arg" in
        --probe) MODE="probe" ;;
        --uninstall) MODE="uninstall" ;;
        --force) FORCE=1 ;;
        --help|-h) MODE="help" ;;
        *) BAD_ARG="$arg"; MODE="help" ;;
    esac
done

if [ "$MODE" = "help" ]; then
    if [ -n "$BAD_ARG" ]; then
        echo "Unknown argument: $BAD_ARG" >&2
        echo "" >&2
    fi
    usage
    [ -n "$BAD_ARG" ] && exit 1
    exit 0
fi

# --- helpers -------------------------------------------------------------

is_ours() {
    # True if $TARGET exists and carries our marker comment near the top.
    [ -e "$TARGET" ] || return 1
    head -n 20 "$TARGET" 2>/dev/null | grep -qF "$MARKER"
}

guard_overwrite() {
    if [ -e "$TARGET" ] && ! is_ours; then
        if [ "$FORCE" != "1" ]; then
            echo "ERROR: '$TARGET' already exists and was not generated by" >&2
            echo "       this installer. Refusing to overwrite it." >&2
            echo "       Re-run with --force if you're sure you want to replace it." >&2
            exit 1
        fi
        echo "WARNING: '--force' given — overwriting a non-generated item at:"
        echo "         $TARGET"
    fi
}

# Write $TARGET from a quoted (no-expansion) heredoc template containing
# __TOKEN__ placeholders, then substitute this machine's real paths in with
# sed. Quoted heredocs are used deliberately so nothing in the wrapper body
# (its own $HOME, $@, $(...), etc.) gets expanded by THIS shell at install
# time — only the explicit __TOKEN__ markers are touched.
render_wrapper() {
    local tmp
    tmp="$(mktemp)"
    cat > "$tmp"
    sed -i '' \
        -e "s|__REPO_DIR__|$REPO_DIR|g" \
        -e "s|__VENV_PYTHON__|$VENV_PYTHON|g" \
        -e "s|__LOG_FILE__|$LOG_FILE|g" \
        -e "s|__CONFIG_DIR__|$CONFIG_DIR|g" \
        "$tmp"
    mv "$tmp" "$TARGET"
    chmod 755 "$TARGET"
    xattr -d com.apple.quarantine "$TARGET" >/dev/null 2>&1 || true
}

write_real_wrapper() {
    render_wrapper <<'WRAPPER_REAL'
#!/bin/bash
# GENERATED by install_pdf_service.sh — do not edit this file by hand.
# Edit tools/install_pdf_service.sh in the tp6s-mac repo instead
# (this machine's checkout: __REPO_DIR__) and re-run it; this wrapper is
# regenerated on every install, not maintained directly.
# MODE: install
#
# What macOS lets this script do is a SHORT list, measured on Darwin 25 by
# printing from TextEdit with a probe installed in this slot:
#
#   allowed   read the spool PDF it is handed; write its own TMPDIR, /tmp
#             and ~/Desktop; read the repo; open a socket to 127.0.0.1
#   DENIED    ~/.venvs (so the venv python cannot be run at all), ~/.config,
#             printtool's own group container, and the notification daemon
#             (so it cannot even tell you what went wrong)
#
# So the wrapper does the only two useful things it can: read the bytes and
# hand them to the helper on 127.0.0.1:8776, which runs unsandboxed from a
# terminal and does the rendering, the printing and the talking. If no helper
# answers it falls back to running the worker directly, which is what happens
# when a person runs this wrapper by hand rather than the print system.
#
# It NEVER exits non-zero: the print system answers a failing workflow item
# with a modal "Error running print workflow" alert that says nothing useful.

set -uo pipefail

REPO_DIR="__REPO_DIR__"
VENV_PYTHON="__VENV_PYTHON__"
HELPER="http://127.0.0.1:8776"

say() { /usr/bin/logger -t TP6S -- "TP6S: $*"; }
note() {
    /usr/bin/osascript -e "display notification \"$1\" with title \"TP6-S\"" \
        >/dev/null 2>&1        # denied under the print system; harmless there
}

say "wrapper invoked, argc=$#"

# The print system's contract is (job title, CUPS options, spool PDF path),
# confirmed on this Mac — but take the last argument that is a readable file
# rather than trusting the position.
TITLE="${1:-}"
PDF=""
for a in "$@"; do
    [ -f "$a" ] && PDF="$a"
done

if [ -z "$PDF" ]; then
    say "no PDF in the arguments — nothing to print"
    note "Nothing to print — no PDF was handed over."
    exit 0
fi

# --- the helper, if it is up ------------------------------------------------
if /usr/bin/curl -s -m 3 "$HELPER/api/status" | /usr/bin/grep -q '"pdf"'; then
    WORK="$(/usr/bin/mktemp -d -t tp6s-pdf)" || WORK="/tmp"
    # JSON built by hand because the only interpreter available here is bash.
    # The title is stripped to characters that cannot break out of a string.
    SAFE="$(printf '%s' "$TITLE" | /usr/bin/tr -d '\\"' | /usr/bin/tr -c 'a-zA-Z0-9 ._-' ' ')"
    {
        printf '{"title":"%s","pdf":"' "$SAFE"
        /usr/bin/base64 -i "$PDF" | /usr/bin/tr -d '\n'
        printf '"}'
    } > "$WORK/body.json"

    say "posting $(/usr/bin/stat -f%z "$PDF") B to the helper"
    OUT="$(/usr/bin/curl -s -m 900 -X POST \
             -H 'Content-Type: application/json' \
             --data-binary @"$WORK/body.json" "$HELPER/api/pdf")"
    /bin/rm -rf "$WORK"
    say "helper replied: $(printf '%s' "$OUT" | /usr/bin/head -c 300)"
    # The helper posts the notification itself — it is the process that knows
    # the outcome, and the only one of the two allowed to speak.
    exit 0
fi

# --- no helper: run the worker directly (only possible outside the sandbox) --
if [ -x "$VENV_PYTHON" ]; then
    say "no helper — running the worker directly"
    "$VENV_PYTHON" "$REPO_DIR/tools/pdf_service.py" "$@"
    say "worker exited $?"
    exit 0
fi

say "no helper on $HELPER, and the venv python is out of reach"
note "Start the helper first: run ./tp6 gui, then print again."
exit 0
WRAPPER_REAL
}

write_probe_wrapper() {
    render_wrapper <<'WRAPPER_PROBE'
#!/bin/bash
# GENERATED by install_pdf_service.sh --probe — do not edit this file by hand.
# Edit tools/install_pdf_service.sh in the tp6s-mac repo instead
# (this machine's checkout: __REPO_DIR__) and re-run it with --probe; this
# wrapper is regenerated on every install, not maintained directly.
# MODE: probe
#
# Diagnostic stand-in for the real "Send to TP6-S" PDF Service. Logs every
# invocation (argv, cwd, env, parent process) instead of printing, so the
# macOS PDF Services invocation contract can be confirmed before the real
# worker is used. This mode is intended only for local diagnosis.
#
# It reports THREE ways on purpose, because the first attempt at this probe
# fired its notification and wrote nothing: `printtool` is reported to
# sandbox the items it launches, and a denied `>>` redirection fails in
# total silence. So:
#
#   1. /usr/bin/logger into the unified log, which a sandbox rarely blocks
#      and which needs no writable directory at all. Read it back with
#      log show --predicate 'eventMessage CONTAINS "TP6SPROBE"' --last 30m
#   2. a full record into EVERY directory that turns out to be writable,
#      out of five candidates, instead of one hard-coded path
#   3. the headline — argc and where it managed to write — inside the
#      notification text itself, so the answer arrives even if all of the
#      above are denied.

set -uo pipefail

CONFIG_DIR="__CONFIG_DIR__"
LOG_FILE="__LOG_FILE__"

TS="$(/bin/date '+%Y-%m-%dT%H:%M:%S%z')"
TS_FILE="$(/bin/date '+%Y%m%dT%H%M%S')"

say() { /usr/bin/logger -t TP6SPROBE -- "$*"; }

say "=== invoked $TS argc=$# ==="
i=0
LAST_FILE=""
for a in "$@"; do
    i=$((i + 1))
    if [ -e "$a" ]; then
        say "arg[$i]=$a (EXISTS, $(/usr/bin/stat -f%z "$a" 2>/dev/null) bytes)"
        LAST_FILE="$a"
    else
        say "arg[$i]=$a"
    fi
done
say "cwd=$PWD uid=$(/usr/bin/id -u) ppid=$PPID parent=$(/bin/ps -o comm= -p "$PPID" 2>/dev/null)"
say "TMPDIR=${TMPDIR:-unset} HOME=${HOME:-unset} PATH=${PATH:-unset}"

# Which of these can this process actually write to? That answer IS the
# finding if the sandbox reports are right.
WROTE=""
for d in "$CONFIG_DIR" "${TMPDIR:-/tmp}" "/tmp" "$HOME/Desktop" \
         "$HOME/Library/Group Containers/group.com.apple.printtool/TemporaryItems"; do
    /bin/mkdir -p "$d" 2>/dev/null
    f="$d/tp6s-probe-$TS_FILE.log"
    if {
        echo "===== TP6-S PDF Service PROBE @ $TS ====="
        echo "argc: $#"
        j=0
        for a in "$@"; do
            j=$((j + 1))
            if [ -e "$a" ]; then
                echo "arg[$j]: $a  (existing file, $(/usr/bin/stat -f%z "$a" 2>/dev/null) bytes, $(/usr/bin/file -b "$a" 2>/dev/null))"
            else
                echo "arg[$j]: $a  (not an existing path)"
            fi
        done
        echo "cwd: $PWD"
        echo "id: $(/usr/bin/id)"
        echo "ppid: $PPID  parent: $(/bin/ps -o comm= -p "$PPID" 2>/dev/null)"
        echo "--- full environment (sorted) ---"
        /usr/bin/env | /usr/bin/sort
        if [ -n "$LAST_FILE" ]; then
            if /bin/cp "$LAST_FILE" "$d/tp6s-probe-$TS_FILE.pdf" 2>/dev/null; then
                echo "spool copy: $d/tp6s-probe-$TS_FILE.pdf (ok)"
            else
                echo "spool copy: FAILED into $d"
            fi
        else
            echo "spool copy: none — no existing-file argument found"
        fi
        echo "===== end probe record ====="
        echo ""
    } >> "$f" 2>/dev/null; then
        say "wrote $f"
        [ -z "$WROTE" ] && WROTE="$d"
    else
        say "DENIED writing to $d"
    fi
done

[ -n "$WROTE" ] || say "NOTHING was writable"

# ---------------------------------------------------------------------------
# What can a job launched by the print dialog actually DO on this Mac? Three
# questions, and between them they decide the whole architecture:
#   1. can it see and run the venv python (~/.venvs is a dot-directory, and
#      the sandbox already denies the other one, ~/.config)?
#   2. can it open a socket to the helper on 127.0.0.1? If yes, the helper
#      can do every bit of the work in an unsandboxed process.
#   3. can it read the spool PDF it was handed? (answered above by the copy)
# ---------------------------------------------------------------------------
VENV_PYTHON="$HOME/.venvs/tp6s/bin/python"
say "test -e venv python: $( [ -e "$VENV_PYTHON" ] && echo YES || echo NO )"
say "test -x venv python: $( [ -x "$VENV_PYTHON" ] && echo YES || echo NO )"
say "ls ~/.venvs: $(/bin/ls "$HOME/.venvs" 2>&1 | /usr/bin/head -c 200)"
say "ls ~/.venvs/tp6s/bin: $(/bin/ls "$HOME/.venvs/tp6s/bin" 2>&1 | /usr/bin/head -c 200)"
say "python runs: $("$VENV_PYTHON" -c "print(1+1)" 2>&1 | /usr/bin/head -c 200)"
say "python imports: $("$VENV_PYTHON" -c "import PIL, Quartz, bleak; print('all three')" 2>&1 | /usr/bin/tail -c 200)"
say "repo readable: $(/bin/ls "__REPO_DIR__/tools/pdf_service.py" 2>&1 | /usr/bin/head -c 200)"
say "curl helper: $(/usr/bin/curl -s -m 3 http://127.0.0.1:8776/api/status 2>&1 | /usr/bin/head -c 200)"
say "curl exit: $?"

/usr/bin/osascript -e "display notification \"argc=$# wrote to: ${WROTE:-NOTHING WRITABLE}\" with title \"TP6-S probe\"" >/dev/null 2>&1

exit 0
WRAPPER_PROBE
}

# --- modes -----------------------------------------------------------------

do_install() {
    local kind="$1"  # "install" or "probe"

    guard_overwrite
    if [ "$kind" = "install" ]; then
        echo "Preparing the optional PDF dependency ..."
        "$REPO_DIR/setup.sh" --pdf
        echo ""
    fi
    mkdir -p "$PDF_SERVICES_DIR"

    if [ "$kind" = "probe" ]; then
        write_probe_wrapper
        echo "Installed the PROBE wrapper as:"
        echo "  $TARGET"
        echo ""
        echo "It will NOT print. It logs every invocation to:"
        echo "  $LOG_FILE"
        echo "and copies the spool PDF next to that log as pdf-probe-<timestamp>.pdf."
        echo ""
        echo "Print anything (e.g. a TextEdit page) via File > Print > PDF >"
        echo "\"Send to TP6-S\", then inspect the log."
    else
        write_real_wrapper
        echo "Installed \"Send to TP6-S\" as:"
        echo "  $TARGET"
        echo ""
        if [ ! -f "$REPO_DIR/tools/pdf_service.py" ]; then
            echo "NOTE: $REPO_DIR/tools/pdf_service.py does not exist yet."
            echo "      Install succeeded, but the menu item will fail until"
            echo "      that file is added to the repo."
            echo ""
        fi
        echo "To use it: open any app's print dialog, open the PDF dropdown"
        echo "(bottom left), and choose \"Send to TP6-S\"."
    fi
}

do_uninstall() {
    if [ -e "$TARGET" ]; then
        if is_ours; then
            rm -f "$TARGET"
            echo "Removed $TARGET"
        else
            echo "$TARGET exists but was not generated by this installer —"
            echo "leaving it alone. Remove it by hand, or re-run install with"
            echo "--force first if you want this installer to own that slot."
            return
        fi
    else
        echo "$TARGET not present; nothing to remove."
    fi

    if [ -d "$PDF_SERVICES_DIR" ]; then
        if [ -z "$(ls -A "$PDF_SERVICES_DIR" 2>/dev/null)" ]; then
            rmdir "$PDF_SERVICES_DIR"
            echo "Removed now-empty $PDF_SERVICES_DIR"
        else
            echo "Left $PDF_SERVICES_DIR in place (other items present)."
        fi
    fi
}

case "$MODE" in
    install) do_install install ;;
    probe) do_install probe ;;
    uninstall) do_uninstall ;;
esac

echo ""
echo "Done."
